feat: Add ability to retrieve payment terms using external id
Vic-ai/api-docs pull request #106
Opened 2024-08-23 19:55 UTC by warmwaffles

* Get a payment term using internal id or external id.
* Update a payment term using internal id or external id.
* Update a payment term's external id.
* Delete a payment term using internal id or external id.
* Create a payment with an external id. Upsert is not implemented, nor will it be.

2024-08-23 23:17 UTC, jonathanpglick requested changes
I think `UpdatePaymentTerm` and `PaymentTerm` objects are both missing `externalId`.

2024-08-23 23:17 UTC, jonathanpglick commented on vic.api.v0.yaml
> +        unspecified **WILL** clear the `externalId`.
```suggestion
        The `id` in the path can be either the Payment Term's internal ID or its external ID
        when `useSystem=external` is included in the request.

        The Payment Term's external ID can be updated by including `externalId={value}`
        in the request body. If the `externalId` key is present without a value, the
        Payment Term's `externalId` **WILL** be cleared.
```

2024-08-23 23:17 UTC, jonathanpglick commented on vic.api.v0.yaml
> +        in order to fetch the payment term.
```suggestion
        The `id` in the path can be either the Payment Term's internal ID or its external ID
        when `useSystem=external` is included in the request.
```

2024-08-24 02:23 UTC, warmwaffles commented on vic.api.v0.yaml
> +        in order to fetch the payment term.
Done. Reused the same description you suggested for `getPaymentTerm`

2024-08-24 02:23 UTC, warmwaffles commented on vic.api.v0.yaml
> +        unspecified **WILL** clear the `externalId`.
Much better.

2024-08-24 02:29 UTC, jonathanpglick approved these changes

2024-08-26 10:15 UTC, mbaleczny approved these changes

2024-08-26 12:55 UTC, merged